<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>preview</LangVersion>
    <EnablePreviewFeatures>True</EnablePreviewFeatures>
    <IsPackable>false</IsPackable>

    <RootNamespace>LaquaiLib.Buffers.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />

    <Using Include="Xunit" />
    <Using Include="System.Runtime.CompilerServices" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LaquaiLib.Buffers\LaquaiLib.Buffers.csproj" />
  </ItemGroup>

</Project>
